version: "2"
services:
  
  base:
    image: quay.io/vektorcloud/locust:latest
    volumes:
      - ${PWD}/locustfile.py:/locust/locustfile.py
    environment:
      - "LOCUST_TARGET=${LOCUST_TARGET}"
    command: -V

  master:
    extends:
      service: base
    ports:
      - 5557
      - 5558
      - 8089:8089
    command: --master --host=${LOCUST_TARGET}

  worker:
    extends:
      service: base
    depends_on:
      - master
    entrypoint: /run.sh
    command: --slave --master-host=master --host=${LOCUST_TARGET}

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
